import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { useStore } from '@nanostores/react';
import { isQuoteModalOpen, closeQuoteModal } from '../store/quoteStore';
export default function QuoteModal(){
 const open=useStore(isQuoteModalOpen),ref=useRef<HTMLDialogElement>(null);
 const [status,setStatus]=useState('idle'),[message,setMessage]=useState('');
 useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement;const overflow=document.body.style.overflow;ref.current?.showModal();document.body.style.overflow='hidden';setStatus('idle');setMessage('');return()=>{document.body.style.overflow=overflow;previous?.focus()}},[open]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus('sending');try{const response=await fetch('/api/send-email',{method:'POST',body:new FormData(e.currentTarget)});const data=await response.json();if(!response.ok||!data.success)throw new Error(data.message||'Please try again.');setStatus('success');setMessage('Thank you. We’ll be in touch to discuss your project.')}catch(error){setStatus('error');setMessage(error instanceof Error?error.message:'Unable to send. Please try again.')}}
 if(!open||typeof document==='undefined')return null;
 return createPortal(<dialog ref={ref} className="quote-dialog" aria-labelledby="quote-title" onCancel={e=>{e.preventDefault();if(status!=='sending')closeQuoteModal()}}><button className="dialog-close" aria-label="Close quote request" disabled={status==='sending'} onClick={closeQuoteModal}>✕</button><h2 id="quote-title">Let’s make it yours.</h2><p>Tell us a little about your project.</p>{status==='success'?<div role="status"><p>{message}</p><button className="button" onClick={closeQuoteModal}>Done</button></div>:<form onSubmit={submit}><input type="checkbox" name="botcheck" hidden tabIndex={-1} aria-hidden="true"/><label htmlFor="quote-name">Your name<input id="quote-name" name="name" autoComplete="name" required/></label><label htmlFor="quote-email">Email<input id="quote-email" type="email" name="email" autoComplete="email" required/></label><label htmlFor="quote-phone">Phone (optional)<input id="quote-phone" type="tel" name="phone" autoComplete="tel"/></label><label htmlFor="quote-message">Your project<textarea id="quote-message" name="message" rows={3} required/></label>{status==='error'&&<p role="alert">{message}</p>}<button className="button" disabled={status==='sending'}>{status==='sending'?'Sending…':'Request a quote ↗'}</button></form>}</dialog>,document.body);
}
